// src/components/StatusBarComponent/StatusBarComponent.tsx
import React, { FC } from 'react';
import styles from './StatusBarComponent.module.scss';
// import Image from 'next/image';

import LogoComponent from "../logo.jsx";
import TimeComponent from '../TimeComponent/TimeComponent';
import GPSComponent from '../GPSComponent/GPSComponent';


export default function StatusBarComponent() {
  function reloadPage() {
    window.location.reload();
  }

  return (<div className={styles.StatusBarComponent}>
    <div className={styles.gpsBox}>
      <GPSComponent></GPSComponent>
    </div>
    <div className={styles.logoBox}>
      {/* <LogoComponent></LogoComponent>
       */}
      <img src="assets/img/logo.png" alt="Logo" width={250} height={40} />
    </div>
    <div className={styles.timeBox}>
      <input type="button" value="Reload page" onClick={reloadPage} />
    </div>
  </div>);
};

// vue-app/src/components/StatusBarComponent/StatusBar.vue
<script lang="ts" setup>
import { ref } from 'vue'
import LogoComponent from '@/components/Logo.vue'
import TimeComponent from '@/components/TimeComponent/TimeComponent.vue'
import GPSComponent from '@/components/GPSComponent/GPSComponent.vue'

const reloadPage = () => {
  window.location.reload()
}
</script>

<template>
  <div class="status-bar">
    <div class="gps-box">
      <GPSComponent />
    </div>
    <div class="logo-box">
      <LogoComponent></LogoComponent>
    </div>
    <div class="time-box">
      <input type="button" value="Reload page" @click="reloadPage" />
    </div>
  </div>
</template>

<style lang="scss" scoped>
.status-bar {
  display: grid;
  grid-template-columns: 1fr auto 1fr;
  align-items: center;
  padding: 1rem;
  
  .gps-box {
    justify-self: start;
  }
  
  .logo-box {
    text-align: center;
  }
  
  .time-box {
    justify-self: end;
  }
}
</style>
