// vue-app/src/components/TimeComponent/TimeComponent.vue
<script lang="ts" setup>
import ErrorHandler from '@/components/ErrorHandlerComponent/ErrorHandler.vue'
import { ref, onMounted, onUnmounted } from 'vue'

const time = ref<Date | null>(null)
let interval: ReturnType<typeof setInterval>

const updateTime = () => {
    time.value = new Date()
}

const formattedTime = computed(() => {
    if (!time.value) return ''

    return new Intl.DateTimeFormat([], {
        hour: '2-digit',
        minute: '2-digit'
    }).format(time.value)
})

onMounted(() => {
    // Set initial time
    updateTime()

    // Update every minute
    interval = setInterval(updateTime, 60000)
})

onUnmounted(() => {
    clearInterval(interval)
})
</script>

<template>
    <div class="time-component">
        <ErrorHandler fallback="Time Unavailable">
            <p class="text-white mb-0">{{ formattedTime }}</p>
        </ErrorHandler>
    </div>
</template>

<style lang="scss" scoped>
.time-component {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    color: #fff;
    ;

    .text-white {
        color: white;
    }

    .mb-0 {
        margin-bottom: 0;
    }
}
</style>

// src/components/TimeComponent/TimeComponent.tsx
import React, { FC } from 'react';
import styles from './TimeComponent.module.scss';

export default function TimeComponent() {
  const [time, setTime] = React.useState<Date | null>(null);

  React.useEffect(() => {
    const interval = setInterval(() => {
      setTime(new Date());
    }, 60000);

    return () => {
      clearInterval(interval);
    };
  }, []);

  const formattedTime = time ? new Date(time).toLocaleString([], {
      hour: '2-digit',
      minute: '2-digit'
  }) : '';

  return (
    <div className={styles.TimeComponent}>
      <p className="text-white mb-0">{formattedTime}</p>
    </div>
  );
};
