// src/views/Home.vue
<script setup lang="ts">
import { ref } from 'vue'
import ToggleSwitch from '@/components/ToggleSwitch/ToggleSwitch.vue'
import GaugesComponent from '@/components/GaugesComponent/GaugesComponent.vue'
import StatusBarComponent from '@/components/StatusBarComponent/StatusBar.vue'
import ErrorHandler from '@/components/ErrorHandlerComponent/ErrorHandler.vue'

interface SwitchPath {
  path: string
  name: string
}

const paths = ref<SwitchPath[]>([
  {
    "path": "electrical.switches.bank.144.1.state",
    "name": "Bilge Pump 1"
  },
  {
    "path": "electrical.switches.bank.144.2.state",
    "name": "Bilge Pump 2"
  },
  {
    "path": "electrical.switches.bank.144.3.state",
    "name": "Bait Tank"
  },
  {
    "path": "electrical.switches.bank.144.4.state",
    "name": "?"
  },
  {
    "path": "electrical.switches.bank.144.5.state",
    "name": "?"
  },
  {
    "path": "electrical.switches.bank.144.6.state",
    "name": "?"
  },
  {
    "path": "electrical.switches.bank.144.7.state",
    "name": "?"
  },
  {
    "path": "electrical.switches.bank.144.8.state",
    "name": "?"
  },
  {
    "path": "electrical.switches.bank.144.9.state",
    "name": "?"
  },
  {
    "path": "electrical.switches.bank.144.10.state",
    "name": "Bilge Blower"
  },
  {
    "path": "electrical.switches.bank.144.11.state",
    "name": "Nav Lights"
  },
  {
    "path": "electrical.switches.bank.144.12.state",
    "name": "Washdown"
  }
])

const handleError = (error: Error): string => {
  return `Error: ${error.message}`
}
</script>

<template>
  <div class="home">
    <ErrorHandler :fallback="handleError">
      <StatusBarComponent />
    </ErrorHandler>

    <div class="gauge-box">
      <ErrorHandler :fallback="handleError">
        <GaugesComponent />
      </ErrorHandler>
    </div>

    <div class="switch-box">
      <ErrorHandler v-for="switchItem in paths" :key="switchItem.path" :fallback="handleError">
        <ToggleSwitch :path="switchItem.path" :name="switchItem.name" />
      </ErrorHandler>
    </div>
  </div>
</template>

<style scoped>
.home {
  width: 100%;
}

.gauge-box {
  display: grid;
  height: 50vh;
}

.switch-box {
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  grid-template-rows: 2;
  background-color: #000;
  height: 40vh;
  color: #fff;
}

.status-box {
  height: 10vw;
}
</style>

// src/components/HomeComponent/HomeComponent.tsx
import React, { FC, useEffect, useState  } from 'react';
import styles from './HomeComponent.module.scss';
import ToggleSwitch from '../ToggleSwitch/ToggleSwitch';
import GaugesComponent from '../GaugesComponent/GaugesComponent';
import StatusBarComponent from '../StatusBarComponent/StatusBarComponent';
import ErrorBoundary from 'components/ErrorBoundaryComponent';

interface HomeComponentProps {}

const HomeComponent: FC<HomeComponentProps> = () => {
  const paths = [
    {
      "path": "electrical.switches.bank.144.1.state",
      "name": "Bilge Pump 1"
    },
    {
      "path": "electrical.switches.bank.144.2.state",
      "name": "Bilge Pump 2"
    },
    {
      "path": "electrical.switches.bank.144.3.state",
      "name": "Bait Tank"
    },
    {
      "path": "electrical.switches.bank.144.4.state",
      "name": "?"
    },
    {
      "path": "electrical.switches.bank.144.5.state",
      "name": "?"
    },
    {
      "path": "electrical.switches.bank.144.6.state",
      "name": "?"
    },
    {
      "path": "electrical.switches.bank.144.7.state",
      "name": "?"
    },
    {
      "path": "electrical.switches.bank.144.8.state",
      "name": "?"
    },
    {
      "path": "electrical.switches.bank.144.9.state",
      "name": "?"
    },
    {
      "path": "electrical.switches.bank.144.10.state",
      "name": "Bilge Blower"
    },
    {
      "path": "electrical.switches.bank.144.11.state",
      "name": "Nav Lights"
    },
    {
      "path": "electrical.switches.bank.144.12.state",
      "name": "Washdown"
    }
  ];

  return (
    <div className={styles.HomeComponent}>
      <ErrorBoundary fallback={<p>Something went wrong</p>}><StatusBarComponent></StatusBarComponent></ErrorBoundary>
      
      <div className={`${styles.gaugeBox}`}>
      <ErrorBoundary fallback={<p>Something went wrong</p>}>
          <GaugesComponent></GaugesComponent>
        </ErrorBoundary>
      </div>
      <div className="">
        <div className={styles.switchBox}>
        { paths.map((value) => (
          <div key={value.path}>
            <ErrorBoundary fallback={<p>Something went wrong</p>}>
            
            <ToggleSwitch path={value.path} name={value.name} />
            </ErrorBoundary>
          </div>
        )) }
        </div>
      </div>
    </div>
  );
};

export default HomeComponent;
